"""add numbering fields to leads contacts leave_requests payroll_runs performance_reviews project_risks project_issues

Revision ID: 200af55576d5
Revises: d8e2f5a1b3c4
Create Date: 2026-03-30 16:28:27.769383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '200af55576d5'
down_revision: Union[str, None] = 'd8e2f5a1b3c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('code', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_contacts_code'), 'contacts', ['code'], unique=False)
    op.create_unique_constraint('uq_contact_code', 'contacts', ['tenant_id', 'code'])
    op.add_column('leads', sa.Column('code', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_leads_code'), 'leads', ['code'], unique=False)
    op.create_unique_constraint('uq_lead_code', 'leads', ['tenant_id', 'code'])
    op.add_column('leave_requests', sa.Column('number', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_leave_requests_number'), 'leave_requests', ['number'], unique=False)
    op.create_unique_constraint('uq_leave_request_number', 'leave_requests', ['tenant_id', 'number'])
    op.add_column('payroll_runs', sa.Column('number', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_payroll_runs_number'), 'payroll_runs', ['number'], unique=False)
    op.create_unique_constraint('uq_payroll_run_number', 'payroll_runs', ['tenant_id', 'number'])
    op.add_column('performance_reviews', sa.Column('number', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_performance_reviews_number'), 'performance_reviews', ['number'], unique=False)
    op.create_unique_constraint('uq_performance_review_number', 'performance_reviews', ['tenant_id', 'number'])
    op.add_column('project_issues', sa.Column('number', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_project_issues_number'), 'project_issues', ['number'], unique=False)
    op.create_unique_constraint('uq_project_issue_number', 'project_issues', ['tenant_id', 'number'])
    op.add_column('project_risks', sa.Column('number', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_project_risks_number'), 'project_risks', ['number'], unique=False)
    op.create_unique_constraint('uq_project_risk_number', 'project_risks', ['tenant_id', 'number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_project_risk_number', 'project_risks', type_='unique')
    op.drop_index(op.f('ix_project_risks_number'), table_name='project_risks')
    op.drop_column('project_risks', 'number')
    op.drop_constraint('uq_project_issue_number', 'project_issues', type_='unique')
    op.drop_index(op.f('ix_project_issues_number'), table_name='project_issues')
    op.drop_column('project_issues', 'number')
    op.drop_constraint('uq_performance_review_number', 'performance_reviews', type_='unique')
    op.drop_index(op.f('ix_performance_reviews_number'), table_name='performance_reviews')
    op.drop_column('performance_reviews', 'number')
    op.drop_constraint('uq_payroll_run_number', 'payroll_runs', type_='unique')
    op.drop_index(op.f('ix_payroll_runs_number'), table_name='payroll_runs')
    op.drop_column('payroll_runs', 'number')
    op.drop_constraint('uq_leave_request_number', 'leave_requests', type_='unique')
    op.drop_index(op.f('ix_leave_requests_number'), table_name='leave_requests')
    op.drop_column('leave_requests', 'number')
    op.drop_constraint('uq_lead_code', 'leads', type_='unique')
    op.drop_index(op.f('ix_leads_code'), table_name='leads')
    op.drop_column('leads', 'code')
    op.drop_constraint('uq_contact_code', 'contacts', type_='unique')
    op.drop_index(op.f('ix_contacts_code'), table_name='contacts')
    op.drop_column('contacts', 'code')
    # ### end Alembic commands ###
